packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@parcel/watcher': false
  '@prisma/client': set this to true or false
  better-sqlite3: set this to true or false
  esbuild: false
  msw: false
  sharp: false
  unrs-resolver: false

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
